version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_ecommerce
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerce
    ports:
      - "3306:3306"
    networks:
      - app_network
    volumes:
      - mysql_data:/var/lib/mysql

networks:
  app_network:
    driver: bridge

volumes:
  mysql_data:
