CREATE TABLE IF NOT EXISTS product_discounts (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `productId` INT UNSIGNED NOT NULL,
  `discountPercent` DECIMAL(5,2) UNSIGNED NOT NULL,
  `startDate` DATETIME NOT NULL,
  `endDate` DATETIME NOT NULL,
  `createdAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

  PRIMARY KEY (`id`),
  FOREIGN KEY (`productId`) REFERENCES products(`id`) ON DELETE CASCADE
);