CREATE TABLE IF NOT EXISTS cart_items (
  `cartId` INT UNSIGNED NOT NULL,
  `productId` INT UNSIGNED NOT NULL,
  `quantity` INT UNSIGNED NOT NULL DEFAULT 1,
  `priceAtAdding` DECIMAL(10,2) UNSIGNED NOT NULL,
  `addedAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

  PRIMARY KEY (`cartId`, `productId`),
  FOREIGN KEY (`cartId`) REFERENCES carts(`id`) ON DELETE CASCADE,
  FOREIGN KEY (`productId`) REFERENCES products(`id`) ON DELETE CASCADE
);