CREATE TABLE IF NOT EXISTS order_history (
    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `userId` INT UNSIGNED NOT NULL,
    `totalAmount` DECIMAL(10,2) UNSIGNED NOT NULL,
    `status` ENUM('PENDING', 'COMPLETED', 'CANCELLED', 'SHIPPED') NOT NULL DEFAULT 'PENDING',
    `paymentMethod` ENUM('CREDIT_CARD', 'DEBIT_CARD', 'PIX', 'BANK_TRANSFER') NOT NULL,
    `paymentId` VARCHAR(255),
    `createdAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updatedAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    FOREIGN KEY (`userId`) REFERENCES users(`id`) ON DELETE CASCADE,
    INDEX `idx_order_user` (`userId`),
    INDEX `idx_order_status` (`status`)
);